---
- hosts: all
  any_errors_fatal: true
  roles:
  - role: common

- hosts: nodes
  any_errors_fatal: true
  roles:
  - role: galera-node

- hosts: haproxy
  any_errors_fatal: true
  roles:
  - role: galera-lb