---
- name: Generate MariaDB Configuration galera.cnf in MariaDB Galera Node
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: "{{ mariadb_file_owner }}"
    group: "{{ mariadb_file_owner }}"
    mode: 0644

- name: Allow SSH in UFW in MariaDB Galera Node
  ufw:
    rule: allow
    port: 22
    proto: tcp
  
- name: Allow port for MariaDB with TCP in MariaDB Galera Node
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 3306
    - 4444
    - 4567
    - 4568

- name: Allow port for MariaDB with UDP in MariaDB Galera Node
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items:
    - 4567

- name: Status UFW in MariaDB Galera Node
  shell: ufw status
  register: ufw_status_info

- name: Intiate/Boostraping cluster MariaDB Galera in MariaDB Galera Node
  shell: galera_new_cluster
  when:
    - primary

- name: Wait For MariaDB Node Service in MariaDB Galera Node
  wait_for:
    port: "{{ mariadb_port }}"
    timeout: 30
    connect_timeout: 5
    delay: 5
    state: present
  when:
    - primary

