---
- name: Reload MariaDB Service in MariaDB Galera Node
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk

- name: Get MariaDB Node Service Info in MariaDB Galera Node
  shell: service mariadb status | grep not-found || true
  args:
    warn: false
  register: mariadb_service_info
  when:
    - service_init_status.stat.exists

- name: Enable MariaDB Node Service in MariaDB Galera Node
  service:
    name: mariadb
    enabled: yes
    state: restarted
  when:
    - inventory_hostname != groups['nodes'] | first
    - mariadb_service_info.stdout.find("not-found") == -1

- name: Wait For MariaDB Node Service in MariaDB Galera Node
  wait_for:
    port: "{{ mariadb_port }}"
    timeout: 30
    connect_timeout: 5
    delay: 5
    state: present
  when:
    - inventory_hostname != groups['nodes'] | first