---
- name: Reload MariaDB Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk

- name: Get MariaDB Node Service Info
  shell: service mysql status | grep not-found || true
  args:
    warn: false
  register: mysql_service_info
  when:
    - service_init_status.stat.exists

- name: Enable MariaDB Node Service
  service:
    name: mysql
    enabled: yes
    state: restarted
  when:
    - mysql_service_info.stdout.find("not-found") == -1

- name: Wait For MariaDB Node Service
  wait_for:
    port: 3306
    timeout: 15
    connect_timeout: 3
    delay: 5
    state: present
