---
- name: Remove Exsisting haproxy.cfg and haproxy.log in Load Balancer Node
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/haproxy/haproxy.cfg
    - /var/log/haproxy.log

- name: Remove IP Address of all hosts MariaDB Galera Node in Load Balancer Node
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ hostvars[item].mariadb_ip }} {{ hostvars[item].ansible_hostname }} "
    state: absent
  with_items: "{{ groups.nodes }}"