---
- include: facts.yml

- include: mariadb_services.yml
  when: 
    - inventory_hostname in groups['nodes']

- include: mariadb_configs.yml
  when:
    - inventory_hostname in groups['nodes']

- include: mariadb_packages.yml
  when:
    - inventory_hostname in groups['nodes']
    - full_uninstall

- include: haproxy_configs.yml
  when:
    - inventory_hostname in groups['haproxy']

- include: haproxy_services.yml
  when:
    - inventory_hostname in groups['haproxy']

- include: haproxy_packages.yml
  when:
    - inventory_hostname in groups['haproxy']


# - include: zfs_mounts.yml
#   when:
#     - full_uninstall
#     - zfs_backend
#     - inventory_hostname in groups['nodes']

# - include: zfs_blocks.yml
#   when:
#     - full_uninstall
#     - zfs_backend
#     - inventory_hostname in groups['nodes']
