---
- name: Remove Exsisting galera.cnf
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql/
  when:
    - full_uninstall

- name: Remove DB
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql/