---
- name: Get MariaDB Node Service Info
  shell: service mariadb status | grep not-found || true
  args:
    warn: false
  register: mariadb_service_info
  when:
    - service_init_status.stat.exists

- name: Disable MariaDB Node Service
  service:
    name: mariadb
    enabled: no
    state: stopped
  when:
    - mariadb_service_info.stdout.find("not-found") == -1

# - name: Get MariaDB Router Service Info
#   shell: service mongos status | grep not-found || true
#   args:
#     warn: false
#   register: mongos_service_info
#   when:
#     - service_init_status.stat.exists

# - name: Disable MariaDB Router Service
#   service:
#     name: mongos
#     enabled: no
#     state: stopped
#   when:
#     - mongos_service_info.stdout.find("not-found") == -1

# - name: Remove MariaDB Router Service (Init)
#   file:
#     path: /etc/init.d/mongos
#     state: absent
#   when:
#     - service_init_status.stat.islnk is defined
#     - not service_init_status.stat.islnk

# - name: Remove MariaDB Router Service (SystemD)
#   file:
#     path: /etc/systemd/system/mongos.service
#     state: absent
#   when:
#     - service_init_status.stat.islnk is defined
#     - service_init_status.stat.islnk

- name: Reload MariaDB Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk
