---
- name: Uninstall MariaDB Packages (MariaDB) in MariaDB Galera Node
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - rsync
    - mariadb-server
  when:
    - mariadb_distribution == 'mariadb-server'

- name: Uninstall MariaDB Repository (MariaDB) in MariaDB Galera Node
  file:
    path: "/etc/apt/sources.list.d/mariadb-server-{{ mariadb_version_major }}.{{ mariadb_version_minor }}.list"
    state: absent
  when:
    - mariadb_distribution == 'mariadb-server'

- name: Uninstall MariaDB Keyring (MariaDB) in MariaDB Galera Node
  apt_key:
    id: '0xF1656F24C74CD1D8'
    state: absent
  when:
    - mariadb_distribution == 'mariadb-server'