---
- name: Get MariaDB Node Service Info
  shell: service mysql status | grep not-found || true
  args:
    warn: false
  register: mariadb_service_info
  when:
    - service_init_status.stat.exists

- name: Disable MariaDB Node Service
  service:
    name: mariadb
    enabled: no
    state: stopped
  when:
    - mariadb_service_info.stdout.find("not-found") == -1

