---
- name: Install HAProxy and MariaDB Client Packages in Load Balancer
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - haproxy
    - mariadb-client