---
- include: facts.yml

- include: os_packages.yml

- include: python_packages.yml

- include: zfs_packages.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['nodes']

- include: zfs_blocks.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['nodes']

- include: zfs_mounts.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['nodes']

- include: mariadb_packages.yml
  when:
    - inventory_hostname in groups['nodes']

- include: mariadb_secure_installation.yml
  when:
    - inventory_hostname in groups['nodes']

- include: mariadb_services.yml
  when:
    - inventory_hostname in groups['nodes']

- include: haproxy_packages.yml
  when:
    - inventory_hostname in groups['haproxy']

- include: haproxy_services.yml
  when:
    - inventory_hostname in groups['haproxy']
