---
- name: Install MariaDB Keyring (MariaDB)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0xF1656F24C74CD1D8'
    state: present
  when:
    - mariadb_distribution == 'mariadb-server'

- name: Install MariaDB Repository (MariaDB)
  lineinfile:
    dest: "/etc/apt/sources.list"
    line: "deb [arch=amd64,arm64,i386,ppc64el] http://kartolo.sby.datautama.net.id/mariadb/repo/{{ mariadb_version_major }}.{{ mariadb_version_minor }}/ubuntu {{ ansible_distribution_release }} main"
    create: yes
    state: present
  when:
    - mariadb_distribution == 'mariadb-server'

- name: Setting mariadb server root pass before installing
  debconf:
    name: "mariadb-server"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "password"
  changed_when: false
  no_log: true
  with_items:
    - question: 'mysql-server/root_password'
      value: '{{ mariadb_admin_password }}'
    - question: 'mysql-server/root_password_again'
      value: '{{ mariadb_admin_password }}'

- name: Install MariaDB Packages (MariaDB)
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - mariadb-server
    - rsync
    - python-mysqldb
  when:
    - mariadb_distribution == 'mariadb-server'

# - name: configure_root_access | updating root passwords
#   mysql_user:
#     name: root
#     host: "{{ item }}"
#     password: "{{ mariadb_admin_password }}"
#   with_items:
#     - '{{ ansible_hostname }}'
#     - '127.0.0.1'
#     - '::1'
#     - localhost