---

- name: Generate MariaDB Configuration .my.cnf in MariaDB Galera Node
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Set Root Password in MariaDB Galera Node 
  mysql_user: 
    login_user: root
    login_password: "{{ mariadb_admin_password }}"
    check_implicit_admin: yes
    name: root
    password: "{{ mariadb_admin_password }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  with_items:
    - "127.0.0.1"
    - "::1"
    - localhost
    - "%"
    - "{{ ansible_hostname }}"

- name: Create User for HAProxy Health Check 
  mysql_user: 
    login_user: root
    login_password: "{{ mariadb_admin_password }}"
    check_implicit_admin: yes
    name: haproxy
    host: "{{ item }}"
  with_items: "{{ groups.haproxy }}"
  when: 
    - primary

- name: Delete Anonymous user in MariaDB Server
  mysql_user: 
    user: ""
    host: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - localhost